### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by igormukhingmailcom** [akeneo/DeltaExportBundle#5]
Hi.

This bundle is deprecated.
What is alternative (to build exporters for Akeneo 1.4)?
Thanks.

**Comment by smalot** [comment]
+1

**Comment by fitn** [comment]
Hi @igormukhingmailcom @smalot 

You can use this bundle: https://github.com/akeneo-labs/EnhancedConnectorBundle
It allows to export products updated since a configurable date :)

Regards,

**Comment by igormukhingmailcom** [comment]
Thank you @fitn :)
